### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wwwwwwwxw** [Ezzud/instify#3]
```js
TypeError: Cannot read properties of undefined (reading 'username')
    at C:\Users\user\Downloads\Code\JavaScript\Instify\app.js:83:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Connected on Spotify as: User
C:\Users\User\Downloads\Code\JavaScript\Instify\app.js:150
                username: profile.username,
                                  ^

TypeError: Cannot read properties of undefined (reading 'username')
    at Timeout._onTimeout (C:\Users\User\Downloads\Code\JavaScript\Instify\app.js:150:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by Ezzud** [comment]
New Instagram API doesn't work anymore, project is outdated
